all: main.o max.o min.o diff.o sum.o
	gcc main.o max.o min.o diff.o sum.o
main.o: main.c max.h min.h diff.h sum.h
	gcc -c main.c
max.o: max.c max.h
	gcc -c max.c
min.o: min.c min.h
	gcc -c min.c
diff.o: diff.c diff.h max.h min.h
	gcc -c diff.c
sum.o: sum.c sum.h
	gcc -c sum.c
	